export const FETCH_STARTED = 'BLOG/FETCH_STARTED';
export const FETCH_SUCCESS = 'BLOG/FETCH_SUCCESS';
export const FETCH_FAILURE = 'BLOG/FETCH_FAILURE';
export const SET_PAGE = 'BLOG/SET_PAGE';
export const SET_ARCHIVE = 'BLOG/SET_ARCHIVE';